# Generated by Django 4.0.4 on 2022-04-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=4000)),
                ('pages', models.IntegerField()),
                ('categories', models.CharField(max_length=200)),
                ('ratingaverage', models.IntegerField()),
                ('ratingnumber', models.IntegerField()),
                ('thumbnail', models.CharField(max_length=200)),
                ('bigthumbnail', models.CharField(max_length=200)),
            ],
        ),
    ]
